const {test,expect}=require('@playwright/test');
test('planes: cuatro accesos, selección provisional, confirmar fijo y persistencia',async({page})=>{
  await page.addInitScript(()=>sessionStorage.setItem('excelia-popup-dismissed','1'));
  await page.goto('/');await page.locator('#eventsBtn').click();await page.locator('#evViewUpcoming').click();await page.locator('#evAdd').click();
  const quick=page.locator('[data-quick=plans]>button');await expect(quick).toHaveCount(4);
  expect(await quick.allTextContents()).toEqual(['Comida','Tomar algo','Cena','Más opciones']);
  await page.locator('#evFTypePicker [data-type="Cena"]').click();
  await page.locator('[data-picker=plans]').click();await page.locator('#evPlanPickerOv [data-type="Brunch"]').click();
  await expect(page.locator('#evFTitle')).toHaveValue('Cena');
  await page.locator('#evPlanCancel').click();await expect(page.locator('#evPlanPickerWrap')).toHaveCount(0);
  await expect(page.locator('#evFTitle')).toHaveValue('Cena');
  await page.locator('[data-picker=plans]').click();await page.locator('#evPlanPickerOv [data-type="Ponencia"]').click();
  await expect(page.locator('.ev-plan-header [data-type="Plan/Quedada"]')).toHaveText('');
  await expect(page.locator('.ev-plan-options [data-type="Plan/Quedada"]')).toHaveCount(0);
  await expect(page.locator('#evPlanConfirm')).toBeInViewport();
  await page.locator('#evPlanPickerOv [data-type="Brunch"]').click();await page.locator('#evPlanConfirm').click();
  await expect(page.locator('#evFTitle')).toHaveValue('Brunch');await expect(page.locator('#evFTime')).toHaveValue('');
  await expect(page.locator('#evPlanPickerWrap')).toHaveCount(0);
  await page.locator('#evFTime').click();await expect(page.locator('#timePickerHours')).toHaveAttribute('aria-valuenow','11');
  await page.locator('#timePickerCancel').click();await expect(page.locator('#timePickerWrap')).toHaveCount(0);
  await page.locator('#evFSave').click();await expect(page.locator('#evFWrap')).toHaveCount(0);
  expect(await page.evaluate(()=>EVENTS[0].type)).toBe('Brunch');expect(await page.evaluate(()=>EVENTS[0].time)).toBeFalsy();
  await page.evaluate(()=>openEvForm(EVENTS[0]));await expect(page.locator('[data-picker=plans]')).toContainText('Brunch');
  await page.locator('#evFSave').click();await expect(page.locator('#evFWrap')).toHaveCount(0);
  expect(await page.evaluate(()=>EVENTS[0].type)).toBe('Brunch');
});
