'use strict';
const assert=require('assert');
const {cargarApp}=require('./entorno');
const a=cargarApp({});
const near=(x,y)=>assert.ok(Math.abs(x-y)<1e-8,`${x} != ${y}`);
const t=a.energyTariffDefaults({energyMode:'tramos',periodPrices:[0.3,0.2,0.1],periodWeights:[20,30,50],terminoFijo:6});
a.energyValidateTariff(t);near(a.energyWeightedPrice(t),0.17);
near(a._calcGasCost(t,100,30),23);
near(a._calcElectCost(t,{potenciaTotal:3},100,30),23);
near(a._calcGasCost({modo:'fijo',cuotaFija:40},999,15),20);
near(a._calcElectCost({precioKwh:0.2,modoPotencia:'doble',precioPotP1:0.1,precioPotP2:0.02,terminoFijo:6},{potenciaP1:3,potenciaP2:3},100,30),36.8);
assert.throws(()=>a.energyValidateTariff({...t,periodWeights:[20,20,20]}));
assert.throws(()=>a.energyValidateTariff({...t,precioKwh:Infinity}));
assert.throws(()=>a.energyValidateTaxes([null]));
assert.throws(()=>a.energyValidateTaxes([{kind:'gas',start:'2026-02-30',rate:21}]));
const taxes=[{kind:'luz',start:'2026-01-01',rate:0},{kind:'luz',start:'2026-01-16',rate:20}];
assert.equal(a.energyVatAt(taxes,'gas','2026-01-16'),null);
assert.equal(a.energyVatAt(taxes,'luz','2026-01-15'),0);
const bill={id:'b1',kind:'luz',supplier:'Ejemplo',number:'A',issued:'2026-02-05',start:'2026-01-01',end:'2026-01-31',consumption:310,net:31,gross:34.2,paid:20,notes:'',source:''};
const months=a.energyConsumptionMonths([bill],2026,'luz');
near(months[0].consumption,310);assert.equal(months[1].count,0);
const simple=a.energyTariffDefaults({precioKwh:0.1});
near(a.energySimulateMonth(months[0],simple,'luz',taxes,false).gross,34.2);
assert.equal(a.energySimulateMonth(months[0],simple,'luz',[],false).gross,null);
const flat=a.energyTariffDefaults({modo:'fijo',cuotaFija:31,promotion:3.1});
near(a.energySimulateMonth(months[0],flat,'luz',taxes,true).gross,31.1);
const crossed={...bill,start:'2025-12-16',end:'2026-01-15',consumption:310};
near(a.energyConsumptionMonths([crossed],2025,'luz')[11].consumption,160);
near(a.energyConsumptionMonths([crossed],2026,'luz')[0].consumption,150);
const adjacent={...bill,id:'b2',number:'B',start:'2026-01-31',end:'2026-02-28',consumption:290};
const joined=a.energyConsumptionMonths([bill,adjacent],2026,'luz');
assert.equal(joined[0].overlap,false);near(joined[0].consumption+joined[1].consumption,600);
const overlap=a.energyConsumptionMonths([bill,{...adjacent,start:'2026-01-20'}],2026,'luz');
assert.equal(a.energySimulateMonth(overlap[0],simple,'luz',taxes,false),null);
const unknown=a.energyConsumptionMonths([{...bill,consumption:null}],2026,'luz');
assert.equal(a.energySimulateMonth(unknown[0],simple,'luz',taxes,false),null);
const zero=a.energyConsumptionMonths([{...bill,consumption:0}],2026,'luz');
near(a.energySimulateMonth(zero[0],flat,'luz',taxes,false).gross,34.2);
const dst=a.energyConsumptionMonths([{...bill,start:'2026-03-01',end:'2026-03-31'}],2026,'luz');near(dst[2].consumption,310);
a.energySaveTaxes(taxes);const before=a.energyImportHistory({energyTaxes:[{kind:'luz',start:'2026-01-16',rate:10}]});
assert.equal(a.energyTaxes().length,2);assert.equal(a.energyVatAt(a.energyTaxes(),'luz','2026-01-20'),10);
a.energyRestoreHistory(before);assert.equal(a.energyVatAt(a.energyTaxes(),'luz','2026-01-20'),20);
assert.throws(()=>a.energyImportHistory({energyTaxes:[{kind:'gas',start:'x',rate:21}]}));
assert.equal(a.energyTaxes().length,2);
console.log('Energía: compatibilidad, ponderación, cuota fija, prorrateo, IVA y restauración OK');

const uncredited=a.energyConsumptionMonths([{...bill,consumption:0,noReading:true}],2026,'luz');
assert.equal(a.energySimulateMonth(uncredited[0],simple,'luz',taxes,false),null);
assert.equal(a.energyMergeBills([{...bill,noReading:true}],[bill])[0].noReading,true);
a.showToast=()=>{};
a.energySendToScenarios({id:'send-test',kind:'luz',supplier:'Ejemplo',tariff:'Tramos',analysis:t});
a.energySendToScenarios({id:'send-test',kind:'luz',supplier:'Ejemplo',tariff:'Tramos',analysis:t});
assert.equal(a.DESPACHO.electComparaciones.length,1);
near(a.DESPACHO.electComparaciones[0].precioKwh,0.17);
near(a._calcElectCost(a.DESPACHO.electComparaciones[0],{},100,30),23);
console.log('Energía: lectura no acreditada y copia idempotente a escenarios OK');
