const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {cargarApp}=require('./entorno');
const a=cargarApp({});
const first=a.tasksCreate('Colgar cuadro'),second=a.tasksCreate('Comprar'),third=a.tasksCreate('Llamar');
assert.equal(a.tasksItems(a.tasksData(),'pending').length,3);
assert(a.tasksMove(third,first,false));
assert.deepEqual(Array.from(a.tasksData().items,t=>t.id),[third,first,second]);
a.tasksChange(first,'complete');assert.equal(a.tasksItems(a.tasksData(),'done').length,1);
a.tasksChange(first,'delete');assert.equal(a.tasksItems(a.tasksData(),'trash').length,1);
a.tasksChange(first,'restore');assert.equal(a.tasksItems(a.tasksData(),'done')[0].id,first);
a.tasksChange(first,'complete');assert.equal(a.tasksItems(a.tasksData(),'pending').length,3);
a.tasksChange(first,'delete');let deleted=a.tasksData(),now=a.Date.now();
assert.equal(a.tasksPrune(deleted,now+a.TASKS_RETENTION-1).items.length,3);
assert.equal(a.tasksPrune(deleted,now+a.TASKS_RETENTION).items.length,2);
assert.equal(deleted.items.length,3,'La purga pura no modifica el origen');
let current=a.tasksData(),incoming=JSON.parse(JSON.stringify(current));
incoming.items[1].title='Título antiguo';incoming.items[1].updatedAt--;
let merged=a.tasksMerge(current,incoming);assert.equal(merged.items.length,3);assert.equal(merged.items[1].title,'Colgar cuadro');assert.equal(merged.items[1].deletedAt,now);
a.tasksReminderSeen(new a.Date());assert.equal(a.tasksReminder(new a.Date()).length,0);
assert.equal(a.tasksReminder(new a.Date('2026-08-24T10:00:00')).length,2);
const disabled=a.tasksData();disabled.weeklyReminder=false;a.tasksSave(disabled);assert.equal(a.tasksReminder(new a.Date('2026-08-24T10:00:00')).length,0);
assert.throws(()=>a.tasksCreate(' '));assert.throws(()=>a.tasksCreate('x'.repeat(161)));
assert.throws(()=>a.validateImport({tasks:{items:[{}],weeklyReminder:true,reminderWeek:''}}));
assert.throws(()=>a.validateImport({tasks:{...current,items:[current.items[0],current.items[0]]}}));
let malicious=JSON.parse(JSON.stringify(current));malicious.items[0].title='<img onerror="alert(1)">';
assert(!a.renderTasks(malicious,'pending').includes('<img onerror='));
assert(a.renderTasks(malicious,'pending').includes('&lt;img'));
// Exportar de verdad, restaurar, fusionar dos veces y simular fallo de disco.
let exportClick,download;
a.document.getElementById=id=>id==='exportAllBtn'?{addEventListener:(_,fn)=>exportClick=fn}:null;
a.document.createElement=()=>({click(){download=JSON.parse(decodeURIComponent(this.href.split(',').slice(1).join(',')));}});
vm.runInContext(fs.readFileSync('js/import-export.js','utf8'),a);a.showToast=()=>{};exportClick();
assert.deepEqual(JSON.parse(JSON.stringify(download.tasks)),JSON.parse(JSON.stringify(a.tasksData())));
const b=cargarApp({});vm.runInContext(fs.readFileSync('js/import-export.js','utf8'),b);b.showToast=()=>{};b.render=()=>{};b.updateEventsBtn=()=>{};b.updateBdayBtn=()=>{};
b.applyFullImport({tasks:download.tasks},'replace');b.applyFullImport({tasks:download.tasks},'merge');
assert.equal(JSON.stringify(b.tasksData()),JSON.stringify(a.tasksData()));
b.applyFullImport({days:{}},'replace');assert.equal(b.tasksData().items.length,3,'Los backups antiguos no borran tareas');
const before=b.localStorage.getItem(b.TASKS_KEY),put=b.localStorage.setItem;let fail=true;
b.localStorage.setItem=(key,value)=>{if(fail&&key===b.TASKS_KEY){fail=false;throw Error('Quota');}put(key,value);};
b.applyFullImport({tasks:{items:[],weeklyReminder:true,reminderWeek:''}},'replace');assert.equal(b.localStorage.getItem(b.TASKS_KEY),before);
b.applyFullImport({tasks:{items:[],weeklyReminder:true,reminderWeek:''}},'replace');assert.equal(b.tasksData().items.length,0);
console.log('Tareas: prioridad, completar, papelera 7 días, recordatorio semanal, backup, fusión y rollback OK');
// Todas las categorías fijas comparten Gestión y sobreviven a la importación.
Object.keys(a.EV_MANAGEMENT_SUBTYPES).forEach(type=>{
 const ev={id:type==='Médico'?'doctor':'test-'+a.EV_MANAGEMENT_SUBTYPES[type],kind:'puntual',type,title:type,start:'2026-08-21',end:'2026-08-21',color:'#ff0000'};
 assert.equal(a.evFilterGroup(ev),'Rec. Gestiones');assert.equal(a.evMarkPriority(ev),0);
 assert.equal(a.getEvDisplayColor(ev),a.evTypeColor('puntual',type));
 assert(a.evMarkerHtml(ev,'','','circle').includes('ev-shape-'+a.EV_MANAGEMENT_SUBTYPES[type]));
 a.validateImport({events:[ev]});assert(a.evAdmiteRepeticion('puntual',type));
});
const form=a.renderEvForm(null);['beer','mountain','rings'].forEach(shape=>assert(form.includes('data-shape="'+shape+'"')));
const group=a.rutDayMarkersHtml([{id:'a',_rut:{id:'r',name:'Pádel',color:'#a3e635'},_rutTime:'16:00',_rutDur:60},{id:'b',_rut:{id:'r',name:'Pádel',color:'#a3e635'},_rutTime:'17:00',_rutDur:60}],' past-marker','2026-08-20');
assert.equal((group.match(/past-marker/g)||[]).length,1);assert(group.includes('rut-marker-group past-marker'));
console.log('Marcadores: gestión compartida, colores fijos, nuevas formas y atenuación de la pila OK');
